### ISSUE TITLE
generator fix

### ISSUE THREAD

**Issue by MartinBucko** [KrakenTyP-co/ToIIoT#1]
Generator nemaze stare data. Cez vikend sa nazbieralo okolo 80K zaznamov. Mozeme to optimalizovat? Napr nech sem tam zmaze starsie data ako den dva alebo tak neako? Za tyzden+ toho bude strasne vela :)

Vdaka.

**Comment by KrakenTyio** [comment]
mno jednoducha pomoc je nastavit vacsie intervali na generatore

Ale bohate postaci ak zakomentujes to generovanie,.. Splnilo testovaci ucel.
Pre dalsie rozsirovanie budeme informovat.

**Comment by KrakenTyio** [comment]
https://github.com/KrakenTyP-co/ToIIoT/commit/f02e2f8ec36cd29d486f81f81c1730a7804d4cfb

**Comment by MartinBucko** [comment]
vdaka, updated...
